from langchain_ollama import ChatOllama
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from config.config import settings
from src.utils.logger import logger, log_error_cleanly
from src.prompt_engineering.prompts import ROUTER_SYSTEM_PROMPT

def get_intent_route(user_input: str):
    """The traffic router: Decides the type of the log based on user's query

    Args:
        user_input (str): The query provided by user.
    """
    logger.info(f"Routing request for input: '{user_input[:50]}...'") # Log 
    
    llm = ChatOllama(model=settings.SMALL_OLLAMA_MODEL_NAME, temperature=0)
    
    system_prompt = ROUTER_SYSTEM_PROMPT
    
    # Using a strict prompt to ensure it only returns one word.
    prompt = ChatPromptTemplate.from_messages([
        ("system", system_prompt),
        ("user", "{input}")
    ])
            
    # Initializing chain
    chain = prompt | llm | StrOutputParser()
    
    # Returning the reponse generated by the LLM
    try:
        intent = chain.invoke({"input": user_input}).strip().upper()
        
        logger.info(f"Router decision: {intent}")
        
        return intent
    
    except Exception as e:
        log_error_cleanly(e)
        